### ISSUE TITLE
plugins do not receive the config object

### ISSUE THREAD

**Issue by amenadiel** [requirejs/alameda#10]
It seems that in callplugin (https://github.com/requirejs/alameda/blob/master/alameda.js#L905) an empty object is hardcoded as the config object.

**Comment by jrburke** [comment]
Right, I am hoping to be more strict in the plugin API, not leak data that maybe should not be leaked. 

In an r.js build, there would at least be an `isBuild: true` in there, but for config that needs to be passed to the loader plugin, what about using [module config](http://requirejs.org/docs/api.html#config-moduleconfig) instead? That works in requirejs/r.js and alameda, and I feel it would work more consistently across AMD loaders.

**Comment by amenadiel** [comment]
Well, in this case it will still pass an empty object since it's hardcoded. I already tried module config before closing down on alameda's callPlugin method, and I agree on using module config for specific config keys but it would break BC for popular plugins such as hbs and jsx loaders. 

BTW, although I love alameda, earlier today I switched to cajon, mostly because I found that bundled prim implementation behaves differently from manually included prim. The former returns the resolution parameter, whereas the latter returns the promise itself.

**Comment by jrburke** [comment]
This is fixed in 0.3.1, but note that 0.3.0 now [assumes there is a native promise implementation](https://github.com/requirejs/alameda#alameda). For [alameda-prim](https://github.com/requirejs/alameda-prim) I did update the internal prim used to be the latest 0.0.7 release.

**Comment by amenadiel** [comment]
Besides the promise polyfill, is there an advantage of alameda instead of cajón? Perhaps I missed some "thenable" method, but cajón already uses xhr to benefit from http2

**Comment by jrburke** [comment]
For HTTP2, the XHR vs script src usage should not matter: the browser/server connection will want to try to optimize the connections regardless of the JS API triggering the network call. The bigger issue is that HTTP2 works better when the server has a graph of the modules and preemptively pushes them to the client. However, that means some server middleware understanding the module graph, something that I do not think is common yet.

cajon's difference is that it can load commonjs modules, ones that do not use define() to wrap the module contents, directly, by using XHR and eval. So if you have modules in that form that cannot be converted to AMD modules, that would be a reason to use cajon.
