### ISSUE TITLE
Fluent API for loading/defining moules

### ISSUE THREAD

**Issue by xwisdom** [requirejs/alameda#16]
Hello James,

I like the changes that you have made to alameda but I have also been thinking about a new Fluent API for loading and defining modules. 

What do you think about the following API?

```javascript
define
.import('admin/foo')
.import('user/info')
.import('Blog from common/lib')
    //  module code 
.module(function(foot, info, blog) {
    // your code here
})

require
.import('repo/scanner')
.import('common/search')
.then(function(scanner,search){
    // your code here
})
```

You will still be able to use the existing define() and require() method.

```javascript
define(['user/info'], function(info){
    // your code here
})
```

Keep up the good work.

Best regards,
__
Raymond Irving

**Comment by jrburke** [comment]
Comparing to this:

```javascript
define(function(require) {
  var foo = require('admin/foo'),
        info = require('user/info'),
        blog = require('common/lib').Blog;
  // your code here
});
```

I do not see that much of an advantage. Plus this [sugared syntax](http://requirejs.org/docs/whyamd.html#sugar) has the benefit of aligning the local names with the module IDs, which is advantageous when the dependencies are more than three.

It also seems to match better with the ES2015 module syntax, where each import is a statement inside the module body.

I have thought about allowing a `require(function(require) {  var a = require('a')})` that would allow this same sort of local name to module ID alignment, but at this point with the native module system getting closer and closer, I do not think there is a lot of collective community energy in seeing new variants for AMD API syntax.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by xwisdom** [comment]
Thanks for the quick response. 

How well does the sugared syntax work with JS compilers like Google Closure? Will alameda still be able to correctly parse the code of the compiled JS?

**Comment by jrburke** [comment]
The r.js optimizer will normalize the define() calls so that it parses out the dependencies and sets up the dependency array, so that it works after minification. alameda could also be changed to handle parsing the minified form, but it means creating a new regexp for each factory function and extra Function toString parsing. 

So alameda just does what requirejs does, and rely on the optimizer normalization. For build bundles, define() calls need to be normalized anyway, for inserting the module ID.
