### ISSUE TITLE
HTML Init, not loading with js ext.

### ISSUE THREAD

**Issue by Saturate** [requirejs/alameda#19]
I using `1.0.0` and I am trying to init my code using:

```html
<script
   data-main="/Components/Framework/PlayerAccountManagement/Scripts/Main" 
   src="/Components/Framework/ScriptLibraries/Scripts/alameda.js">
</script>
```

This is trying to load `https://example.com/Components/Framework/PlayerAccountManagement/Scripts/Main`, and this does not exist, as we are missing the `.js` extension.

I did the following to get around it, but it's pretty ugly.

```html
<script
   data-main="/Components/Framework/PlayerAccountManagement/Scripts/Main.js.js" 
   src="/Components/Framework/ScriptLibraries/Scripts/alameda.js">
</script>
```
I don't really have any other configuration for alameda, so have i forgotten something?

**Comment by jrburke** [comment]
I am having trouble reproducing the issue with 1.0.0. I did the following under my web server root:

```
mkdir temp
cd temp
mkdir node_modules
npm install alameda
```

Then in that test directory I created this test.html page:

```html
<!DOCTYPE html>
<html>
<head>
<script
   data-main="/Components/Framework/PlayerAccountManagement/Scripts/Main"
   src="/temp/node_modules/alameda/alameda.js">
</script>
</head>
<body>
</body>
</html>
```

I then loaded it in Firefox and I see in the developer tools that there is a request made for `http://127.0.0.1/Components/Framework/PlayerAccountManagement/Scripts/Main.js`, which is what I would expect, no need to bother with the .js.js change.

I confirmed that alameda 1.0.0 was installed with that npm command, tried in Chrome 52 and Firefox 49.0a2 so I am not sure what might be causing the reported issue. Perhaps the alameda.js file was corrupted somehow, or there is more to the test/html page than what is mentioned above?

Closing this ticket for now, just to keep the bug list under control, but please continue discussion here and we can reopen if we find something that needs fixing.

**Comment by Saturate** [comment]
Found the bug, and the issue was mine. Had forgotten that I had changed the file with the following:

```
var myGlobalRequire = (function () {
    //Define a require object here that has any
    //default configuration you want for RequireJS. If
    //you do not have any config options you want to set,
    //just use an simple object literal, {}. You may need
    //to at least set baseUrl.
    var require = {
        baseUrl: '..'
    };

    //INSERT require.js CONTENTS HERE

    return require;
}());
```
Source: http://requirejs.org/docs/faq-advanced.html

And it seems like the following broke the loading of my main module.

```
    var require = {
        baseUrl: '..'
    };
```

Sorry, and thanks for your time!
