### ISSUE TITLE
Module is not loaded, if normalized ids dependencies differ, but they are resolved to the same url

### ISSUE THREAD

**Issue by betalb** [requirejs/alameda#21]
If we configure paths in such a manner, that the same module can be referenced by different id's, only one of them will be loaded, and every module, that depends on second id won't be loaded

**Directory tree structure**
```
/modules/
  - common-module.js
  - module1.js
  - module2.js
/index.html
/main.js
```

**config**
```
{
    paths: {
        'some-crazy-path': './modules',
        'common-module-path': './modules/common-module',
    },
}
```

**common-module.js**
```
define(function (requrie) {
    return 'common-module';
});
```

**module1.js**
```
define(function (require) {
	return 'module-1-' + require('some-crazy-path/common-module');
});
```

**module2.js**
```
define(function (require) {
	return 'module-2-' + require('common-module-path');
});
```

**main.js**
```
define(function (require) {
	var modules = [];
	
	modules.push(require('modules/module1'));
	modules.push(require('modules/module2'));

	alert('everything was loaded: [' + modules.join(', ') + ']');
});
```

In module1 we referenced common module using aliased directory + module name, that resides in this directory. In module2 we used full alias of common module. Alameda and RequireJs both treat those modules as different, but when time comes, to load file for the second time, they will check loaded urls index, and won't load, becuase both modules were resolved to the same url, and it was already loaded

**Comment by jrburke** [comment]
This sounds similar to https://github.com/requirejs/requirejs/pull/1601, see the discussion there. No plans to support this, best to normalize the IDs, or use [map config](http://requirejs.org/docs/api.html#config-map) to point the one module ID to the other module ID to avoid the issue.

**Comment by betalb** [comment]
Thank you for clarification
