### ISSUE TITLE
Is defining with name supported?

### ISSUE THREAD

**Issue by nazar-pc** [requirejs/alameda#22]
I didn't find this as unsupported functionality and run into series of issues with libraries that define modules with explicit name.
For instance: https://github.com/guardian/html-janitor/blob/f3a8364d1b0907f2b3a4da6f0f116d7298a41292/src/html-janitor.js#L3

**Comment by jrburke** [comment]
It is a bit unfortunate if they are naming their modules, but it should be possible for it to work if a config (like a paths config) is set up so that 'html-janitor' resolves to the URL at the location where that file is installed.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by nazar-pc** [comment]
Sorry for not providing configuration. I've prepared minimal demo so that you can reproduce an issue: https://github.com/nazar-pc/alameda-issue-22
It resolves to `undefined` instead of function.

Yes, they (Guardian) have many repositories with named modules, I've tired manually patching them to overcome this issue, but upstream changes in their libraries (with their build systems) might be even more difficult.

**Comment by jrburke** [comment]
With package config, the loader creates an internal mapping for the package "main" module to match the package name, but wants to still load the module under the "main" module name.

In the case of that example repo, the "main" module ID is: `html-janitor/src/html-janitor`.

If you use paths config instead, then it works out:

```javascript
	require.config({
		paths: {
			'html-janitor': 'node_modules/html-janitor/src/html-janitor'
		}
	});
```

I think you had another issue around some packages that had internal package dependencies, and packages config does work best for those. So if you have one that has internal package dependencies, then paths config is not an option.

In that case, what I would do instead is to have a prebuild step that would remove the name from the `define` calls in those packages. If you prefer to not touch the node_modules source to do that, then you could use the [onBuildRead option](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) in the config passed to r.js to use a regexp and remove the names for the selected names/modules as the contents of the module are read into the optimizer.

**Comment by nazar-pc** [comment]
I do not want to use any build system here. I'd like to always have sources that can work without multi-layer build systems.

I did have issues with paths (for instance, `lodash-amd` didn't work well with them), so I've converted everything to packages. The above config is only a part of the story, such configuration options are generated from `bower.json` and `package.json` contents and I need an algorithm how to write those configs that all of the packages work well with it.

Don't you think this is a bug that should be fixed? I mean there is a pretty clear path:
* require(['html-janitor'], ...) is called
* node_modules/html-janitor/src/html-janitor.js file is loaded
* node_modules/html-janitor/src/html-janitor.js defines `html-janitor` package
* require(['html-janitor'], ...) resolves to `undefined`

This is a great source of confusion. Is it possible to fix this without breaking existing tests?

**Comment by jrburke** [comment]
Packages are a bit weird because exterior modules to it need to use 'packagename' to access it, while modules internal to it often use the a relative path to the specifically named file, and those need to resolve to the same module. The existing packages support I think is a way that satisfies both of those needs.

The proper fix is for the packages to not include the name in the UMD wrapper for these modules. Modules in source form should not be named so that it is possible to refer to them as the consumer wishes.

**Comment by nazar-pc** [comment]
It feels way too complex. Would be much easier to reason if `./path` calls being resolved as relative paths and `path` being resolved as specified in configuration.

I do not see anything specific about `packages` or `paths` in AMD spec, it seems to be RequireJS-specific.

**What do you think about making one single exception - treat `define('package_name', ...)` as `define(...)` when it happens within `package_name` source?** I believe no one will ever rely on `package_name` defined within such file to be relative.

I also see other packages like this: https://github.com/guardian/scribe-plugin-inline-styles-to-elements (`scribe-plugin-inline-styles-to-elements` on NPM).
They're using build system with `plumber-requirejs` that turns multiple files into one, where:
```javascript
define([
  './inline-styles-formatter',
  './as-html-formatter'
], function (
  inlineStylesFormatter,
  asHtmlFormatter
) {
```
gets converted into:
```javascript
define('scribe-plugin-inline-styles-to-elements',[
  './inline-styles-formatter',
  './as-html-formatter'
], function (
  inlineStylesFormatter,
  asHtmlFormatter
) {
```
And thus it doesn't work with `packages` config.

**Comment by jrburke** [comment]
There is some info on common config for AMD loaders here:
https://github.com/amdjs/amdjs-api/blob/master/CommonConfig.md

It is a separate piece from the base define() module declaration API since it does not deal with declaring modules.

I will think about it more, I might consider a pull request for something like "if module ID matches the name of a package, consider it the "main" module. Blerg, but that most likely will run afoul of the work the r.js optimizer does to serialize the "packagename" module to depend on the "packagename/main" module, so that packages config is not required for small AMD API providers like [almond](https://github.com/requirejs/almond).

This is definitely an incorrect thing those packages are doing though, so it bothers me to have to work around their bad practice.

**Comment by nazar-pc** [comment]
I'll definitely send PR if I come up with something like you've described.
Those packages might do something wrong, but since it seems to be a common issue, it is virtually impossible to fix everywhere. Maintaining lots of forks is not fun either (I already maintain few of them with out-of-tree patches).

**Comment by ScottFreeCode** [comment]
My two cents' worth: I've always thought that the name parameter is basically broken outside of bundling; as nice as it would be if it were useful somehow (for instance, it would have been really awesome if paths weren't so involved in module resolution so we could all use the name parameter and bundle just by concatenating the files; but who ever heard of a way to look up modules except by the path...), if it's not, then maybe simply making it either invalid or ignored would be better than the current behavior where the only correct thing to do is not to use it but if you use it anyway it's somehow everybody else's problem.

**Comment by jrburke** [comment]
Thinking about this more, I am more likely to get bug reports of issues where the package main and packagename modules after a build get mixed up. PR #23 is an incomplete solution, and only applies to alameda, not for requirejs/almond/r.js building, other related loaders.

So I think it best to focus on either fixing the output in the repos that are naming those modules, as that is not best practice for single module files, or using a project-specific solution if fixing those packages are not an option.

For instance, the project could create a [npm scripts](https://docs.npmjs.com/misc/scripts) script that it can run after doing an npm install, which would do a glob search for .js files in the packages and do a regexp replace to remove the name in the file, something like `content.replace(/define\s*\(\s*['"][^'"]+['"]\s*,/, 'define('`.

I know that second option is not ideal, but I do not like bloating the loader for trying to counteract bad practices by modules, and this situation a possible change has ripple effects across repos.

Alternatively, if you find that PR #23 is enough for your project, it is completely reasonable to maintain a fork of alameda for your project in that case.
