### ISSUE TITLE
Two requirejs compatibility differences

### ISSUE THREAD

**Issue by chadaustin** [requirejs/alameda#28]
When porting from requirejs to alameda, we discovered two compatibility differences:

in onResourceLoad `map.name` became `map.id`.

Also, `context.contextName` became `context.id`.

Might be worth documenting or adding a compat getter?

**Comment by jrburke** [comment]
Hmm, looks like there are quite a few differences:
https://github.com/requirejs/requirejs/wiki/Internal-API:-onResourceLoad

Given the amount of differences, I'm wondering if it is worth just a readme document section with a translation section. Thoughts?

**Comment by chadaustin** [comment]
Documentation would be totally fine with me. :)
