### ISSUE TITLE
errback doesn't seem to catch() on the promise chain

### ISSUE THREAD

**Issue by dgoldstein0** [requirejs/alameda#32]
I expected that

```
require(foo, success, error)
```

to be equivalent to

```
require(foo).then(success).catch(error)
```

However this doesn't seem to be the case right now.  Test case:

```
require([], function(){console.log("success"); throw new Error("trial");}, function(){console.log("errback")}).catch(function(){console.log("caught error")})
```

triggers all 3 log statements, whereas

```
require([]).then(function(){console.log("success"); throw new Error("trial");}).catch(function(){console.log("errback")}).catch(function(){console.log("caught error")})
```

only triggers the first two.

**Comment by jrburke** [comment]
The last example needs to throw from the first catch to print all the errors. If a catch() does not throw, the error is considered "handled" and further catch() chains are not invoked, rather the .then(success) case is followed. For the last example to get all three:

```javascript
require([]).then(function(){
    console.log("success"); 
    throw new Error("trial");
}).catch(function(){
    console.log("errback")
    // THROW HERE to reach final catch()
    throw new Error('another');
}).catch(function(){
    console.log("caught error")
});
```

This is just normal promise behavior, so closing at a discussion topic.
