### ISSUE TITLE
Can you take this off?

### ISSUE THREAD

**Issue by jacksao** [requirejs/alameda#42]
```js
urlRegExp = /^\/|\:|\?|\.js$/ 
// ==> 
urlRegExp = /^\/|\:|\?/ 
```
https://github.com/requirejs/alameda/blob/6408eb1b6eed13fd53d616f2fd2835d174e572b5/alameda.js#L21

**Comment by jrburke** [comment]
This regexp is constructed like that to match the [requirejs rules for loading IDs as URLs](http://requirejs.org/docs/api.html#jsfiles). For the sake of that compatibility, there are no plans to change it. However, you could decide to fork the library and make the change in that fork if it worked better for your own project's needs.
