### ISSUE TITLE
importing `foo.js` is not the same as importing `foo`

### ISSUE THREAD

**Issue by dgoldstein0** [requirejs/alameda#43]
```
requirejs.config({paths: {bar: "compiled/bar"}, baseUrl: "https://cdn.com/static/"});
require(["bar"]);
require(["bar.js"]);
```

expected: both load `https://cdn.com/static/compiled/bar.js`
actual: the first one works as expected; the second one loads bar.js relative to the current page instead - ignoring the paths config and the baseUrl.

what's even weirder is that `require.toUrl("bar")` and `require.toUrl("bar.js")`returns `https://cdn.com/static/compiled/bar` and `https://cdn.com/static/compiled/bar.js` respectively, which does not match what gets loaded.  I would expect both of them to return the second version, though it's more important for this to at least resemble what actually gets loaded in the second case.

As far as a fix, from reading the code my guess is that this has something to do with `if (urlRegExp.test(moduleName))` in `nameToUrl`; I'm not sure why that branch matches things ending in `.js`.  Additionally though the logic to look up the paths config also does the wrong thing if .js is on the module name, so perhaps the best option is to trim the .js at the beginning of the function and proceed as if it weren't there.

**Comment by dgoldstein0** [comment]
for a slight bit of motivation, I ran into this because I'm working with rollups experimental code splitting emitting AMD, and it likes to output relative urls like `./chunk-abcd.js`; and the imports of those run into this behavior.

**Comment by jrburke** [comment]
This behavior is a holdover from the requirejs behavior of supporting plain URL loading](https://requirejs.org/docs/api.html#jsfiles). In retrospect, I feel it was a mistake to try to support it since it does result in some unexpected behavior now that people are more used to module identifiers. No plans to change it for historical API matching reasons. Maybe in a major version rev, but I do not see that happening any time soon.

**Comment by dgoldstein0** [comment]
huh, I did not realize this was the requirejs behavior too.  Unfortunate, since it definitely feels counterintuitive that foo and foo.js aren't considered the same thing.  Maybe I've just been taught to expect the two to be the same by nodejs module resolution.

Anyhow, perhaps this ".js is a url" behavior could be behind an option of some kind?  I don't even have a problem with `:` and `/` implying it's a url, as those aren't normal things in module specifiers - just the part about ending in .js implying the string is a url is surprising to me.

Is the toUrl behavior also expected, or is that a bug?

**Comment by dgoldstein0** [comment]
Ahhh I was not aware of nodeIdCompat, that looks like exactly what I need.
I'll give that a shot.  Thanks for the tip!

**Comment by dgoldstein0** [comment]
it works!  thanks for that tip.

Going to close this issue, though I do feel the toUrl api is wonky and it's behavior here makes no sense to me.
