### ISSUE TITLE
module.uri is an empty string

### ISSUE THREAD

**Issue by dasa** [requirejs/alameda#49]
https://github.com/requirejs/alameda/blob/897dd4cbd42e63f97630144281e5a2176f872d30/alameda.js#L884

It's set in `requirejs` here: https://github.com/requirejs/requirejs/blob/master/require.js#L596

Is this a bug or by design? It looks like it could be fixed by passing the url to the function here:
 https://github.com/requirejs/alameda/blob/897dd4cbd42e63f97630144281e5a2176f872d30/alameda.js#L1075

**Comment by jrburke** [comment]
Fixed in #50
