### ISSUE TITLE
Feature request: return a promise from async require

### ISSUE THREAD

**Issue by ewinslow** [requirejs/alameda#8]
If you want a promise for a module, you need to do:

```js
var someDepPromise = new Promise(function(resolve, reject) {
    require(['some/dep'], resolve, reject)
});
```

This is boilerplatey. I'd really prefer just doing:

```js
var someDepPromise = require(['some/dep']);
```

Or, more explicitly:

```js
var someDepPromise = require.async('some/dep');
```

This would be my preference. I find changing function semantics based on argument types to be confusing.

I was going to request this for requirejs, but figured alameda would be a better place for it since it has prim.

**Comment by ewinslow** [comment]
More background on what is motivating this

Consider a module with an async dependency:

```js
define(function(require) {
  return function doSomethingAsync() {
    return new Promise(function(resolve, reject) {
      require(['dep'], function(dep) {
        // actually do the thing.
      });
   });
  }
});
```

This suffers from two problems, as I see it:
 * There is a whole lot of function nesting: AMD, the function itself, the promise, the require callback.
 * The async module is not requested until the function is called, though it could be requested earlier. So this is a missed performance optimization opportunity.

Being able to request async dependencies at the top level but then only use them when needed would be great. And doing so with promises would remove the need for the `new Promise` declaration, so that just removes some boilerplate. IMHO it is also more readable, since it allows you to keep all dependencies, sync and async, in one place at the top of the file:

```js
define(function(require) {
  var depPromise = require.async('dep');

  return function doSomethingAsync() {
    return depPromise.then(function(dep) {
        // actually do the thing.
    });
  }
});
```

**Comment by jrburke** [comment]
What I am prototyping in https://github.com/amodrojs/amodro-lifecycle/tree/master/impl/amd is a require([]) return value that is a promise, but it is chained after the function callback, since Promise.all() returns an array as the resolved value (so the callback to require([]) is still nice for shorthand).

The end result would be something like this:

```javascript
require(['a', 'b'], function(a, b) {
  // Do something with a and b, any
  // return result is what is passed to
  // then listeners.
  return somethingNew;
}).then(function(value) {
  //value is now somethingNew
}).catch(function(err) {
  // catches then errors but also errors
  // in original require() callback.
});
```

I want to prove that out some more in that test implementation, but want to move in that general direction. So definitely plans to move in that direction. No ETA yet though on it, want to solidify the lifecycle primitive first.

**Comment by gbaumgart** [comment]
Hi, 
the link is dead. Did you progressed with that? I am looking for anything which turns require into a full valid promise or Deferred (shouldn't it be from beginning like that?)
